class Admin::Staffing::StaffController < Admin::BaseController
  def index
    @breadcrumbs = [
      { name: "ダッシュボード", path: admin_dashboard_path },
      { name: "手配管理", path: admin_staffing_staff_index_path },
      { name: "スタッフ管理", path: admin_staffing_staff_index_path }
    ]

    # KPIサマリー
    @summary = {
      total_staff: 158,
      active: 142,
      on_assignment: 128,
      available: 14,
      inactive: 16,
      cert_expiring_soon: 8
    }

    # スタッフ一覧
    @staff = [
      {
        id: 1,
        code: "ST-0001",
        name: "山本太郎",
        age: 35,
        gender: "男性",
        phone: "090-1111-1111",
        email: "yamamoto@staff.example.com",
        location: "東京都",
        work_status: "稼働中",
        current_project: "東京モーターショー2025",
        skills: ["接客", "英語", "VIP対応", "イベント経験"],
        skill_level: "上級",
        certifications: ["TOEIC 900点", "イベント検定"],
        hourly_rate: 3_500,
        assignment_count: 15,
        rating: 4.8,
        last_assignment_date: "2025-11-01",
        availability_date: nil,
        remarks: nil
      },
      {
        id: 2,
        code: "ST-0002",
        name: "鈴木花子",
        age: 28,
        gender: "女性",
        phone: "080-2222-2222",
        email: "suzuki@staff.example.com",
        location: "神奈川県",
        work_status: "稼働中",
        current_project: "結婚式サポート",
        skills: ["接客", "フォーマル対応", "配膳経験", "ブライダル経験"],
        skill_level: "中級",
        certifications: ["ブライダルコーディネーター"],
        hourly_rate: 3_000,
        assignment_count: 8,
        rating: 4.5,
        last_assignment_date: "2025-10-15",
        availability_date: nil,
        remarks: nil
      },
      {
        id: 3,
        code: "ST-0003",
        name: "田中一郎",
        age: 42,
        gender: "男性",
        phone: "090-3333-3333",
        email: "tanaka@staff.example.com",
        location: "東京都",
        work_status: "待機中",
        current_project: nil,
        skills: ["接客", "英語", "中国語", "通訳サポート"],
        skill_level: "上級",
        certifications: ["TOEIC 950点", "中国語検定2級"],
        hourly_rate: 4_000,
        assignment_count: 22,
        rating: 4.9,
        last_assignment_date: "2025-10-31",
        availability_date: "2025-11-15",
        remarks: "即日アサイン可能"
      },
      {
        id: 4,
        code: "ST-0004",
        name: "佐藤美咲",
        age: 26,
        gender: "女性",
        phone: "080-4444-4444",
        email: "sato.m@staff.example.com",
        location: "千葉県",
        work_status: "稼働中",
        current_project: "企業セミナー運営",
        skills: ["接客", "受付", "事務サポート", "PC操作"],
        skill_level: "中級",
        certifications: ["秘書検定2級"],
        hourly_rate: 2_800,
        assignment_count: 6,
        rating: 4.3,
        last_assignment_date: "2025-09-01",
        availability_date: nil,
        remarks: nil
      },
      {
        id: 5,
        code: "ST-0005",
        name: "高橋健太",
        age: 31,
        gender: "男性",
        phone: "090-5555-5555",
        email: "takahashi@staff.example.com",
        location: "東京都",
        work_status: "稼働中",
        current_project: "音楽フェスティバル運営",
        skills: ["イベント経験", "屋外対応", "設営", "機材搬入"],
        skill_level: "上級",
        certifications: ["イベント業務管理者1級", "フォークリフト"],
        hourly_rate: 3_200,
        assignment_count: 18,
        rating: 4.7,
        last_assignment_date: "2025-08-01",
        availability_date: nil,
        remarks: nil
      },
      {
        id: 6,
        code: "ST-0006",
        name: "伊藤里奈",
        age: 29,
        gender: "女性",
        phone: "080-6666-6666",
        email: "ito@staff.example.com",
        location: "埼玉県",
        work_status: "待機中",
        current_project: nil,
        skills: ["接客", "展示会経験", "誘導", "案内"],
        skill_level: "中級",
        certifications: ["イベント検定"],
        hourly_rate: 2_900,
        assignment_count: 10,
        rating: 4.4,
        last_assignment_date: "2025-10-20",
        availability_date: "2025-11-20",
        remarks: "12月から長期案件希望"
      },
      {
        id: 7,
        code: "ST-0007",
        name: "渡辺翔太",
        age: 27,
        gender: "男性",
        phone: "090-7777-7777",
        email: "watanabe@staff.example.com",
        location: "東京都",
        work_status: "稼働中",
        current_project: "国際会議サポート",
        skills: ["接客", "英語", "通訳サポート", "ビジネスマナー"],
        skill_level: "中級",
        certifications: ["TOEIC 850点"],
        hourly_rate: 3_300,
        assignment_count: 7,
        rating: 4.6,
        last_assignment_date: "2025-10-01",
        availability_date: nil,
        remarks: nil
      },
      {
        id: 8,
        code: "ST-0008",
        name: "小林由美",
        age: 33,
        gender: "女性",
        phone: "080-8888-8888",
        email: "kobayashi@staff.example.com",
        location: "神奈川県",
        work_status: "休業中",
        current_project: nil,
        skills: ["接客", "フォーマル対応", "VIP対応", "イベント経験"],
        skill_level: "上級",
        certifications: ["イベント業務管理者1級", "ブライダルコーディネーター"],
        hourly_rate: 3_400,
        assignment_count: 20,
        rating: 4.8,
        last_assignment_date: "2025-09-30",
        availability_date: "2026-01-15",
        remarks: "産休中・1月復帰予定"
      },
      {
        id: 9,
        code: "ST-0009",
        name: "中村健",
        age: 24,
        gender: "男性",
        phone: "090-9999-9999",
        email: "nakamura@staff.example.com",
        location: "東京都",
        work_status: "待機中",
        current_project: nil,
        skills: ["接客", "誘導", "受付", "基本PC操作"],
        skill_level: "初級",
        certifications: nil,
        hourly_rate: 2_500,
        assignment_count: 3,
        rating: 4.2,
        last_assignment_date: "2025-10-25",
        availability_date: "即日",
        remarks: "即日アサイン可能"
      },
      {
        id: 10,
        code: "ST-0010",
        name: "加藤大介",
        age: 38,
        gender: "男性",
        phone: "080-0000-0000",
        email: "kato@staff.example.com",
        location: "東京都",
        work_status: "稼働中",
        current_project: "マラソン大会運営サポート",
        skills: ["イベント経験", "屋外対応", "体力", "早朝対応"],
        skill_level: "上級",
        certifications: ["イベント業務管理者1級", "普通救命講習"],
        hourly_rate: 3_000,
        assignment_count: 25,
        rating: 4.9,
        last_assignment_date: "2025-07-01",
        availability_date: nil,
        remarks: nil
      },
      {
        id: 11,
        code: "ST-0011",
        name: "松本愛",
        age: 30,
        gender: "女性",
        phone: "090-1234-5678",
        email: "matsumoto@staff.example.com",
        location: "千葉県",
        work_status: "稼働中",
        current_project: "音楽フェスティバル運営",
        skills: ["接客", "物販", "レジ操作", "夜間対応"],
        skill_level: "中級",
        certifications: nil,
        hourly_rate: 2_700,
        assignment_count: 9,
        rating: 4.5,
        last_assignment_date: "2025-09-15",
        availability_date: nil,
        remarks: nil
      },
      {
        id: 12,
        code: "ST-0012",
        name: "吉田誠",
        age: 36,
        gender: "男性",
        phone: "080-2345-6789",
        email: "yoshida@staff.example.com",
        location: "東京都",
        work_status: "待機中",
        current_project: nil,
        skills: ["イベント運営", "進行管理", "スタッフ管理", "トラブル対応"],
        skill_level: "上級",
        certifications: ["イベント業務管理者1級", "イベントプロデューサー"],
        hourly_rate: 4_500,
        assignment_count: 30,
        rating: 4.9,
        last_assignment_date: "2025-10-28",
        availability_date: "2025-12-01",
        remarks: "12月から稼働希望"
      }
    ]

    # スキル別集計
    @skill_summary = [
      { skill: "接客", count: 42, avg_rate: 3_100 },
      { skill: "イベント経験", count: 35, avg_rate: 3_200 },
      { skill: "英語", count: 28, avg_rate: 3_600 },
      { skill: "展示会経験", count: 22, avg_rate: 2_900 },
      { skill: "フォーマル対応", count: 18, avg_rate: 3_300 },
      { skill: "VIP対応", count: 15, avg_rate: 3_500 }
    ]

    # 資格有効期限アラート
    @certification_alerts = [
      { staff_name: "山本太郎", certification: "イベント検定", expiry_date: "2025-12-15", days_remaining: 33 },
      { staff_name: "高橋健太", certification: "イベント業務管理者1級", expiry_date: "2025-12-20", days_remaining: 38 },
      { staff_name: "田中一郎", certification: "中国語検定2級", expiry_date: "2026-01-10", days_remaining: 59 }
    ]
  end
end
